version: "3.8"

services:
  springboot-api:
    image: public.ecr.aws/l1s7l1v5/springboard-talent-backend:latest
    container_name: springboard-talent-api-local
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:3001
      - SERVER_SERVLET_CONTEXT_PATH=/api/v1
    restart: unless-stopped
    networks:
      - springboard-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  springboard-network:
    driver: bridge
